# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - clientConfig:
      url: https://$(SERVICE_NAME).$(SERVICE_NAMESPACE).svc/mutate-terminal
    name: mutating-create-update-terminal.gardener.cloud
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - clientConfig:
      url: https://$(SERVICE_NAME).$(SERVICE_NAMESPACE).svc/validate-terminal
    name: validating-create-update-terminal.gardener.cloud
