# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: dashboard.gardener.cloud/v1alpha1
kind: Terminal
metadata:
  annotations:
    dashboard.gardener.cloud/operation: keepalive
  namespace: garden-local
  name: term-garden
spec:
  host:
    credentials:
      serviceAccountRef:
        name: cluster-admin
        namespace: gardentmp
    namespace: shoot--local--local
    pod:
      labels:
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-runtime-apiserver: allowed
        networking.gardener.cloud/to-public-networks: allowed
      container:
        image: europe-docker.pkg.dev/gardener-project/releases/gardener/ops-toolbelt:0.26.0
  target:
    credentials:
      serviceAccountRef:
        name: robot
        namespace: garden-local
    kubeconfigContextNamespace: garden-local
    namespace: garden-local
    authorization:
      projectMemberships:
        - projectName: local
          roles:
            - admin
    apiServer:
      serviceRef:
        name: kubernetes
        namespace: default
