# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: dashboard.gardener.cloud/v1alpha1
kind: Terminal
metadata:
  annotations:
    dashboard.gardener.cloud/operation: keepalive
  namespace: garden-local
  name: term-shoot
spec:
  host:
    credentials:
      serviceAccountRef:
        name: cluster-admin
        namespace: gardentmp
    namespace: shoot--local--local
    pod:
      labels:
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-public-networks: allowed
        networking.gardener.cloud/to-all-shoot-apiservers: allowed
      container:
        image: europe-docker.pkg.dev/gardener-project/releases/gardener/ops-toolbelt:0.26.0
  target:
    credentials:
      shootRef:
        name: local
        namespace: garden-local
    kubeconfigContextNamespace: default
    temporaryNamespace: true
    authorization:
      roleBindings:
        - nameSuffix: -ca
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: cluster-admin
          bindingKind: ClusterRoleBinding
    apiServer:
      serviceRef:
        name: kube-apiserver
        namespace: shoot--local--local
