# options for analysis running
run:
  timeout: 2m
  allow-parallel-runners: true

linters:
  enable:
    - gochecksumtype
    - goimports
    - perfsprint
    - protogetter
    - revive
    - whitespace
    - wsl
linters-settings:
  goimports:
    local-prefixes: github.com/gardener/terminal-controller-manager
issues:
  exclude-rules:
    # Allow dot imports for ginkgo and gomega
    - source: ginkgo|gomega
      linters:
        - revive
      text: "should not use dot imports"
