# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# Adds namespace to all resources.
namespace: terminal-system

namePrefix: terminal- # must match with namePrefix defined in ../../default/kustomization.yaml

commonLabels:
  component: terminal-manager

resources:
- ../../../crd
- ../../../rbac
- ../../../secret # secret needs to be included because of TLSCERT var. The secret itself does not necessarily be applied to the virtual garden
- webhook-admission
- namespace.yaml

vars:
  - name: TLSCERT # somehow this var cannot be defined in the config/webhook-admission/kustomization.yaml
    objref:
      kind: Secret
      version: v1
      name: webhook-server-cert
    fieldref:
      fieldpath: data[tls.crt]
