# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# Adds namespace to all resources.
namespace: terminal-system # namespace must not start with garden- to prevent name clashes with project namespaces

namePrefix: terminal- # must match with namePrefix defined in ../../default/kustomization.yaml

labels:
  - includeSelectors: true
    pairs:
      component: terminal-manager

resources:
- ../../../crd
- ../../../rbac
- ../../../secret # secret needs to be included because of TLSCERT var. The secret itself does not necessarily be applied to the virtual garden
- webhook-admission
- namespace.yaml

replacements:
- source:
    kind: Secret
    version: v1
    name: webhook-server-cert
    fieldPath: data.[tls.crt]
  targets:
  - select:
      name: mutating-webhook-configuration
      kind: MutatingWebhookConfiguration
    fieldPaths:
      - webhooks.[name=mutating-create-update-terminal.gardener.cloud].clientConfig.caBundle
    options:
      create: true
  - select:
      name: validating-webhook-configuration
      kind: ValidatingWebhookConfiguration
    fieldPaths:
    - webhooks.[name=validating-create-update-terminal.gardener.cloud].clientConfig.caBundle
    options:
      create: true
