apiVersion: v1
kind: Service
metadata:
  name: terminal-admission-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: terminal
    app.kubernetes.io/component: admission-controller
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 9443 # TODO expose via configuration
  selector:
    app.kubernetes.io/name: terminal
    app.kubernetes.io/component: controller-manager