#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o pipefail

# For the check step concourse will set the following environment variables:
# SOURCE_PATH - path to component repository root directory.

if [ -z "$SOURCE_PATH" ]; then
  SOURCE_PATH="$(dirname "$0")/.."
fi
export SOURCE_PATH="$(readlink -f "$SOURCE_PATH")"

pushd "${SOURCE_PATH}" > /dev/null

export GOLANGCI_LINT_ADDITIONAL_FLAGS="--verbose --timeout 2m"
export GO_TEST_ADDITIONAL_FLAGS="-race"

if [ "${TEST_COV+yes}" = yes ] ; then
  # supposed to be run in release jobs
  make verify-extended
else
  # run test instead of test-cov to speed-up jobs, as coverage slows down tests significantly
  make check-generate verify
fi

popd > /dev/null
