apiVersion: dashboard.gardener.cloud/v1alpha1
kind: Terminal
metadata:
  annotations:
    dashboard.gardener.cloud/operation: keepalive
  namespace: garden-coretmp
  name: term-garden
spec:
  host:
    credentials:
      serviceAccountRef:
        name: seed-myseed
        namespace: gardentmp
    namespace: shoot--core--mycluster
    pod:
      container:
        image: eu.gcr.io/gardener-project/gardener/ops-toolbelt:0.11.0
  target:
    credentials:
      serviceAccountRef:
        name: robot
        namespace: garden-coretmp
    kubeconfigContextNamespace: garden-coretmp
    namespace: garden-coretmp
    authorization:
      projectMemberships:
        - projectName: core-tmp
          roles:
            - admin
    apiServer:
      server: https://kubernetes.default.svc
