# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# uncomment the lines below and provide kubeconfig with sensible data. Generate a new kubeconfig pointing to the virtual-garden and use the token from the terminal-controller-manager service account residing in the login-system namespace on the virtual garden

#apiVersion: v1
#kind: Secret
#type: opage
#metadata:
#  name: kubeconfig
#  namespace: system
#data:
#  kubeconfig: Cg==
