# SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
description: A Helm chart to deploy the terminal-controller-manager
name: terminal-controller-manager
version: 0.1.0
