name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request: ~
permissions:
  contents: read
env:
  # renovate: datasource=github-releases depName=golangci/golangci-lint
  GOLANG_CI_LINT_VERSION: v1.63.4
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@ec5d18412c0aeab7936cb16880d708ba2a64e1ae # v6.2.0
        with:
          version: ${{ env.GOLANG_CI_LINT_VERSION }}
          args: --verbose --timeout 5m
