name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request: ~
permissions:
  contents: read
env:
  # renovate: datasource=github-releases depName=golangci/golangci-lint
  GOLANG_CI_LINT_VERSION: v1.61.0
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86 # v6.1.0
        with:
          version: ${{ env.GOLANG_CI_LINT_VERSION }}
          args: --verbose --timeout 5m
